// Module included in the following assemblies:
//
// * rosa_getting_started/rosa-getting-started.adoc
// * rosa_getting_started/rosa-quickstart-guide-ui.adoc

:_mod-docs-content-type: PROCEDURE
[id="rosa-getting-started-create-cluster-admin-user_{context}"]
= Create a cluster administrator user for quick cluster access

[role="_abstract"]
Before configuring an identity provider, you can create a user with `cluster-admin` privileges for immediate access to your {product-title} cluster.

[NOTE]
====
The cluster administrator user is useful when you need quick access to a newly deployed cluster. However, consider configuring an identity provider and granting cluster administrator privileges to the identity provider users as required. For more information about setting up an identity provider for your {product-title} cluster, see _Configuring an identity provider and granting cluster access_.
====

.Prerequisites

* You have an AWS account.
* You installed and configured the latest {rosa-cli}, `rosa`, on your workstation.
* You logged in to your Red{nbsp}Hat account using the {rosa-cli}.
* You created a {product-title} cluster.

.Procedure

. Create a cluster administrator user, replacing `<cluster_name>` with the name of your cluster:
+
[source,terminal]
----
$ rosa create admin --cluster=<cluster_name>
----
+
.Example output
[source,terminal]
----
W: It is recommended to add an identity provider to login to this cluster. See 'rosa create idp --help' for more information.
I: Admin account has been added to cluster '<cluster_name>'.
I: Please securely store this generated password. If you lose this password you can delete and recreate the cluster admin user.
I: To login, run the following command:

   oc login https://api.example-cluster.wxyz.p1.openshiftapps.com:6443 --username cluster-admin --password d7Rca-Ba4jy-YeXhs-WU42J

I: It may take up to a minute for the account to become active.
----
+
[NOTE]
====
It might take approximately one minute for the `cluster-admin` user to become active.
====

. Log in to the cluster through the CLI by running the command provided in the output of the preceding step, replacing `<api_url>` and `<cluster_admin_password>` with the API URL and cluster administrator password for your environment:
+
[source,terminal]
----
$ oc login <api_url> --username cluster-admin --password <cluster_admin_password>
----

.Verification

* Verify that you are logged in as the cluster administrator:
+
[source,terminal]
----
$ oc whoami
----
+
.Example output
[source,terminal]
----
cluster-admin
----

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/authentication_and_authorization/understanding-authentication[Understanding authentication]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/authentication_and_authorization/understanding-identity-provider[Understanding identity provider configuration]
* link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/4/html/introduction_to_rosa/policies-and-service-definition[Cluster administration role]
